server:
  port: 8071

spring:
  application:
    name: configserver
  profiles:
    active: git
    #active: native
  cloud:
    config:
      server:
        git:
          uri: "https://github.com/AnantkrJain/spring-cloud-config-central.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
        #native:
          #search-locations: "file:////Users//anantjain//Documents//TechTute//SpringBootMicroservices//BankMicroservices//6_Microservices_Config_Mgmt//config"
          #search-locations: classpath:/config

management:
  endpoints:
    web:
      exposure:
        include: "*"
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true


encrypt:
  key: "5234SGFSAG2S3V4G5N6G1G5G4G3G2G1G"